//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Caller : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Caller(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Caller obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Caller() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigCplusplusPINVOKE.delete_Caller(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Caller() : this(SwigCplusplusPINVOKE.new_Caller(), true) {
  }

  public void setCallback(SimpleCallback ptrCallback) {
    SwigCplusplusPINVOKE.Caller_setCallback(swigCPtr, SimpleCallback.getCPtr(ptrCallback));
  }

  public void resetCallback() {
    SwigCplusplusPINVOKE.Caller_resetCallback(swigCPtr);
  }

  public SimpleCallback getCallBack() {
    global::System.IntPtr cPtr = SwigCplusplusPINVOKE.Caller_getCallBack(swigCPtr);
    SimpleCallback ret = (cPtr == global::System.IntPtr.Zero) ? null : new SimpleCallback(cPtr, false);
    return ret;
  }

  public void call() {
    SwigCplusplusPINVOKE.Caller_call(swigCPtr);
  }

}
