//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SwigCplusplus {
  public static void funcA() {
    SwigCplusplusPINVOKE.funcA();
  }

  public static readonly double PI = SwigCplusplusPINVOKE.PI_get();
}
