//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class triangle : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal triangle(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(triangle obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~triangle() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigCplusplusPINVOKE.delete_triangle(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int a {
    set {
      SwigCplusplusPINVOKE.triangle_a_set(swigCPtr, value);
    } 
    get {
      int ret = SwigCplusplusPINVOKE.triangle_a_get(swigCPtr);
      return ret;
    } 
  }

  public int b {
    set {
      SwigCplusplusPINVOKE.triangle_b_set(swigCPtr, value);
    } 
    get {
      int ret = SwigCplusplusPINVOKE.triangle_b_get(swigCPtr);
      return ret;
    } 
  }

  public int c {
    set {
      SwigCplusplusPINVOKE.triangle_c_set(swigCPtr, value);
    } 
    get {
      int ret = SwigCplusplusPINVOKE.triangle_c_get(swigCPtr);
      return ret;
    } 
  }

  public triangle() : this(SwigCplusplusPINVOKE.new_triangle(), true) {
  }

}
