//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class vec3ds : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<point3d>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vec3ds(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(vec3ds obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~vec3ds() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SwigCplusplusPINVOKE.delete_vec3ds(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public vec3ds(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (point3d element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public point3d this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(point3d[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(point3d[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, point3d[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<point3d> global::System.Collections.Generic.IEnumerable<point3d>.GetEnumerator() {
    return new vec3dsEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new vec3dsEnumerator(this);
  }

  public vec3dsEnumerator GetEnumerator() {
    return new vec3dsEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class vec3dsEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<point3d>
  {
    private vec3ds collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public vec3dsEnumerator(vec3ds collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public point3d Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (point3d)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    SwigCplusplusPINVOKE.vec3ds_Clear(swigCPtr);
  }

  public void Add(point3d x) {
    SwigCplusplusPINVOKE.vec3ds_Add(swigCPtr, point3d.getCPtr(x));
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = SwigCplusplusPINVOKE.vec3ds_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = SwigCplusplusPINVOKE.vec3ds_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    SwigCplusplusPINVOKE.vec3ds_reserve(swigCPtr, n);
  }

  public vec3ds() : this(SwigCplusplusPINVOKE.new_vec3ds__SWIG_0(), true) {
  }

  public vec3ds(vec3ds other) : this(SwigCplusplusPINVOKE.new_vec3ds__SWIG_1(vec3ds.getCPtr(other)), true) {
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
  }

  public vec3ds(int capacity) : this(SwigCplusplusPINVOKE.new_vec3ds__SWIG_2(capacity), true) {
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
  }

  private point3d getitemcopy(int index) {
    point3d ret = new point3d(SwigCplusplusPINVOKE.vec3ds_getitemcopy(swigCPtr, index), true);
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private point3d getitem(int index) {
    point3d ret = new point3d(SwigCplusplusPINVOKE.vec3ds_getitem(swigCPtr, index), false);
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, point3d val) {
    SwigCplusplusPINVOKE.vec3ds_setitem(swigCPtr, index, point3d.getCPtr(val));
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(vec3ds values) {
    SwigCplusplusPINVOKE.vec3ds_AddRange(swigCPtr, vec3ds.getCPtr(values));
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
  }

  public vec3ds GetRange(int index, int count) {
    global::System.IntPtr cPtr = SwigCplusplusPINVOKE.vec3ds_GetRange(swigCPtr, index, count);
    vec3ds ret = (cPtr == global::System.IntPtr.Zero) ? null : new vec3ds(cPtr, true);
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, point3d x) {
    SwigCplusplusPINVOKE.vec3ds_Insert(swigCPtr, index, point3d.getCPtr(x));
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, vec3ds values) {
    SwigCplusplusPINVOKE.vec3ds_InsertRange(swigCPtr, index, vec3ds.getCPtr(values));
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    SwigCplusplusPINVOKE.vec3ds_RemoveAt(swigCPtr, index);
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    SwigCplusplusPINVOKE.vec3ds_RemoveRange(swigCPtr, index, count);
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
  }

  public static vec3ds Repeat(point3d value, int count) {
    global::System.IntPtr cPtr = SwigCplusplusPINVOKE.vec3ds_Repeat(point3d.getCPtr(value), count);
    vec3ds ret = (cPtr == global::System.IntPtr.Zero) ? null : new vec3ds(cPtr, true);
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    SwigCplusplusPINVOKE.vec3ds_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    SwigCplusplusPINVOKE.vec3ds_Reverse__SWIG_1(swigCPtr, index, count);
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, vec3ds values) {
    SwigCplusplusPINVOKE.vec3ds_SetRange(swigCPtr, index, vec3ds.getCPtr(values));
    if (SwigCplusplusPINVOKE.SWIGPendingException.Pending) throw SwigCplusplusPINVOKE.SWIGPendingException.Retrieve();
  }

}
