/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_SwigCplusplus_WRAP_H_
#define SWIG_SwigCplusplus_WRAP_H_

class SwigDirector_SimpleCallback : public SimpleCallback, public Swig::Director {

public:
    SwigDirector_SimpleCallback();
    virtual ~SwigDirector_SimpleCallback();
    virtual void run();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    void swig_connect_director(SWIG_Callback0_t callbackrun);

private:
    SWIG_Callback0_t swig_callbackrun;
    void swig_init_callbacks();
};


#endif
