/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_SwigCplusplus(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_SwigCplusplus(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_SwigCplusplus(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


	#include "CPlusPlusClass.h"
	#include "gmeDefine.h"
	#include "gmeParseObj.h"
	using namespace Smart3dMap;


#include <string>


#include <typeinfo>
#include <stdexcept>


#include <vector>
#include <algorithm>
#include <stdexcept>

SWIGINTERN vector< Smart3dMap::point3d > *new_vector_Sl_Smart3dMap_point3d_Sg___SWIG_2(int capacity){
        std::vector< Smart3dMap::point3d >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< Smart3dMap::point3d >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN Smart3dMap::point3d vector_Sl_Smart3dMap_point3d_Sg__getitemcopy(vector< Smart3dMap::point3d > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN Smart3dMap::point3d const &vector_Sl_Smart3dMap_point3d_Sg__getitem(vector< Smart3dMap::point3d > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void vector_Sl_Smart3dMap_point3d_Sg__setitem(vector< Smart3dMap::point3d > *self,int index,Smart3dMap::point3d const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void vector_Sl_Smart3dMap_point3d_Sg__AddRange(vector< Smart3dMap::point3d > *self,std::vector< Smart3dMap::point3d > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< Smart3dMap::point3d > *vector_Sl_Smart3dMap_point3d_Sg__GetRange(vector< Smart3dMap::point3d > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< Smart3dMap::point3d >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void vector_Sl_Smart3dMap_point3d_Sg__Insert(vector< Smart3dMap::point3d > *self,int index,Smart3dMap::point3d const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void vector_Sl_Smart3dMap_point3d_Sg__InsertRange(vector< Smart3dMap::point3d > *self,int index,std::vector< Smart3dMap::point3d > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void vector_Sl_Smart3dMap_point3d_Sg__RemoveAt(vector< Smart3dMap::point3d > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void vector_Sl_Smart3dMap_point3d_Sg__RemoveRange(vector< Smart3dMap::point3d > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< Smart3dMap::point3d > *vector_Sl_Smart3dMap_point3d_Sg__Repeat(Smart3dMap::point3d const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< Smart3dMap::point3d >(count, value);
      }
SWIGINTERN void vector_Sl_Smart3dMap_point3d_Sg__Reverse__SWIG_0(vector< Smart3dMap::point3d > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void vector_Sl_Smart3dMap_point3d_Sg__Reverse__SWIG_1(vector< Smart3dMap::point3d > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void vector_Sl_Smart3dMap_point3d_Sg__SetRange(vector< Smart3dMap::point3d > *self,int index,std::vector< Smart3dMap::point3d > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }
SWIGINTERN vector< Smart3dMap::triangle > *new_vector_Sl_Smart3dMap_triangle_Sg___SWIG_2(int capacity){
        std::vector< Smart3dMap::triangle >* pv = 0;
        if (capacity >= 0) {
          pv = new std::vector< Smart3dMap::triangle >();
          pv->reserve(capacity);
       } else {
          throw std::out_of_range("capacity");
       }
       return pv;
      }
SWIGINTERN Smart3dMap::triangle vector_Sl_Smart3dMap_triangle_Sg__getitemcopy(vector< Smart3dMap::triangle > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN Smart3dMap::triangle const &vector_Sl_Smart3dMap_triangle_Sg__getitem(vector< Smart3dMap::triangle > *self,int index){
        if (index>=0 && index<(int)self->size())
          return (*self)[index];
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void vector_Sl_Smart3dMap_triangle_Sg__setitem(vector< Smart3dMap::triangle > *self,int index,Smart3dMap::triangle const &val){
        if (index>=0 && index<(int)self->size())
          (*self)[index] = val;
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void vector_Sl_Smart3dMap_triangle_Sg__AddRange(vector< Smart3dMap::triangle > *self,std::vector< Smart3dMap::triangle > const &values){
        self->insert(self->end(), values.begin(), values.end());
      }
SWIGINTERN std::vector< Smart3dMap::triangle > *vector_Sl_Smart3dMap_triangle_Sg__GetRange(vector< Smart3dMap::triangle > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        return new std::vector< Smart3dMap::triangle >(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void vector_Sl_Smart3dMap_triangle_Sg__Insert(vector< Smart3dMap::triangle > *self,int index,Smart3dMap::triangle const &x){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, x);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void vector_Sl_Smart3dMap_triangle_Sg__InsertRange(vector< Smart3dMap::triangle > *self,int index,std::vector< Smart3dMap::triangle > const &values){
        if (index>=0 && index<(int)self->size()+1)
          self->insert(self->begin()+index, values.begin(), values.end());
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void vector_Sl_Smart3dMap_triangle_Sg__RemoveAt(vector< Smart3dMap::triangle > *self,int index){
        if (index>=0 && index<(int)self->size())
          self->erase(self->begin() + index);
        else
          throw std::out_of_range("index");
      }
SWIGINTERN void vector_Sl_Smart3dMap_triangle_Sg__RemoveRange(vector< Smart3dMap::triangle > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        self->erase(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN std::vector< Smart3dMap::triangle > *vector_Sl_Smart3dMap_triangle_Sg__Repeat(Smart3dMap::triangle const &value,int count){
        if (count < 0)
          throw std::out_of_range("count");
        return new std::vector< Smart3dMap::triangle >(count, value);
      }
SWIGINTERN void vector_Sl_Smart3dMap_triangle_Sg__Reverse__SWIG_0(vector< Smart3dMap::triangle > *self){
        std::reverse(self->begin(), self->end());
      }
SWIGINTERN void vector_Sl_Smart3dMap_triangle_Sg__Reverse__SWIG_1(vector< Smart3dMap::triangle > *self,int index,int count){
        if (index < 0)
          throw std::out_of_range("index");
        if (count < 0)
          throw std::out_of_range("count");
        if (index >= (int)self->size()+1 || index+count > (int)self->size())
          throw std::invalid_argument("invalid range");
        std::reverse(self->begin()+index, self->begin()+index+count);
      }
SWIGINTERN void vector_Sl_Smart3dMap_triangle_Sg__SetRange(vector< Smart3dMap::triangle > *self,int index,std::vector< Smart3dMap::triangle > const &values){
        if (index < 0)
          throw std::out_of_range("index");
        if (index+values.size() > self->size())
          throw std::out_of_range("index");
        std::copy(values.begin(), values.end(), self->begin()+index);
      }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_funcA() {
  funcA();
}


SWIGEXPORT double SWIGSTDCALL CSharp_PI_get() {
  double jresult ;
  double result;
  
  result = (double)(3.14);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_CPlusPlusClass_Add(void * jarg1, int jarg2, int jarg3) {
  int jresult ;
  CPlusPlusClass *arg1 = (CPlusPlusClass *) 0 ;
  int arg2 ;
  int arg3 ;
  int result;
  
  arg1 = (CPlusPlusClass *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (int)(arg1)->Add(arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_CPlusPlusClass() {
  void * jresult ;
  CPlusPlusClass *result = 0 ;
  
  result = (CPlusPlusClass *)new CPlusPlusClass();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_CPlusPlusClass(void * jarg1) {
  CPlusPlusClass *arg1 = (CPlusPlusClass *) 0 ;
  
  arg1 = (CPlusPlusClass *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Foo_add(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  Foo *arg1 = (Foo *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  
  arg1 = (Foo *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  arg4 = (int *)jarg4; 
  (arg1)->add(arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Foo_spam1(void * jarg1, void * jarg2) {
  Foo *arg1 = (Foo *) 0 ;
  Foo *arg2 = (Foo *) 0 ;
  
  arg1 = (Foo *)jarg1; 
  arg2 = (Foo *)jarg2; 
  (arg1)->spam1(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Foo_spam2(void * jarg1, void * jarg2) {
  Foo *arg1 = (Foo *) 0 ;
  Foo *arg2 = 0 ;
  
  arg1 = (Foo *)jarg1; 
  arg2 = (Foo *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Foo & type is null", 0);
    return ;
  } 
  (arg1)->spam2(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Foo_spam3(void * jarg1, void * jarg2) {
  Foo *arg1 = (Foo *) 0 ;
  Foo arg2 ;
  Foo *argp2 ;
  
  arg1 = (Foo *)jarg1; 
  argp2 = (Foo *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Foo", 0);
    return ;
  }
  arg2 = *argp2; 
  (arg1)->spam3(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Foo_spam4(void * jarg1, void * jarg2) {
  Foo *arg1 = (Foo *) 0 ;
  Foo *arg2 ;
  
  arg1 = (Foo *)jarg1; 
  arg2 = (Foo *)jarg2; 
  (arg1)->spam4(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Foo() {
  void * jresult ;
  Foo *result = 0 ;
  
  result = (Foo *)new Foo();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Foo(void * jarg1) {
  Foo *arg1 = (Foo *) 0 ;
  
  arg1 = (Foo *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_point3d__SWIG_0() {
  void * jresult ;
  Smart3dMap::point3d *result = 0 ;
  
  result = (Smart3dMap::point3d *)new Smart3dMap::point3d();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_point3d__SWIG_1(double jarg1, double jarg2, double jarg3) {
  void * jresult ;
  double arg1 ;
  double arg2 ;
  double arg3 ;
  Smart3dMap::point3d *result = 0 ;
  
  arg1 = (double)jarg1; 
  arg2 = (double)jarg2; 
  arg3 = (double)jarg3; 
  result = (Smart3dMap::point3d *)new Smart3dMap::point3d(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_point3d_add_point(void * jarg1, void * jarg2) {
  void * jresult ;
  Smart3dMap::point3d *arg1 = (Smart3dMap::point3d *) 0 ;
  Smart3dMap::point3d *arg2 = 0 ;
  Smart3dMap::point3d result;
  
  arg1 = (Smart3dMap::point3d *)jarg1; 
  arg2 = (Smart3dMap::point3d *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Smart3dMap::point3d const & type is null", 0);
    return 0;
  } 
  result = (arg1)->operator +((Smart3dMap::point3d const &)*arg2);
  jresult = new Smart3dMap::point3d((const Smart3dMap::point3d &)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_point3d_x_set(void * jarg1, double jarg2) {
  Smart3dMap::point3d *arg1 = (Smart3dMap::point3d *) 0 ;
  double arg2 ;
  
  arg1 = (Smart3dMap::point3d *)jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT double SWIGSTDCALL CSharp_point3d_x_get(void * jarg1) {
  double jresult ;
  Smart3dMap::point3d *arg1 = (Smart3dMap::point3d *) 0 ;
  double result;
  
  arg1 = (Smart3dMap::point3d *)jarg1; 
  result = (double) ((arg1)->x);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_point3d_y_set(void * jarg1, double jarg2) {
  Smart3dMap::point3d *arg1 = (Smart3dMap::point3d *) 0 ;
  double arg2 ;
  
  arg1 = (Smart3dMap::point3d *)jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT double SWIGSTDCALL CSharp_point3d_y_get(void * jarg1) {
  double jresult ;
  Smart3dMap::point3d *arg1 = (Smart3dMap::point3d *) 0 ;
  double result;
  
  arg1 = (Smart3dMap::point3d *)jarg1; 
  result = (double) ((arg1)->y);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_point3d_z_set(void * jarg1, double jarg2) {
  Smart3dMap::point3d *arg1 = (Smart3dMap::point3d *) 0 ;
  double arg2 ;
  
  arg1 = (Smart3dMap::point3d *)jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->z = arg2;
}


SWIGEXPORT double SWIGSTDCALL CSharp_point3d_z_get(void * jarg1) {
  double jresult ;
  Smart3dMap::point3d *arg1 = (Smart3dMap::point3d *) 0 ;
  double result;
  
  arg1 = (Smart3dMap::point3d *)jarg1; 
  result = (double) ((arg1)->z);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_point3d(void * jarg1) {
  Smart3dMap::point3d *arg1 = (Smart3dMap::point3d *) 0 ;
  
  arg1 = (Smart3dMap::point3d *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_triangle_a_set(void * jarg1, int jarg2) {
  Smart3dMap::triangle *arg1 = (Smart3dMap::triangle *) 0 ;
  int arg2 ;
  
  arg1 = (Smart3dMap::triangle *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->a = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_triangle_a_get(void * jarg1) {
  int jresult ;
  Smart3dMap::triangle *arg1 = (Smart3dMap::triangle *) 0 ;
  int result;
  
  arg1 = (Smart3dMap::triangle *)jarg1; 
  result = (int) ((arg1)->a);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_triangle_b_set(void * jarg1, int jarg2) {
  Smart3dMap::triangle *arg1 = (Smart3dMap::triangle *) 0 ;
  int arg2 ;
  
  arg1 = (Smart3dMap::triangle *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->b = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_triangle_b_get(void * jarg1) {
  int jresult ;
  Smart3dMap::triangle *arg1 = (Smart3dMap::triangle *) 0 ;
  int result;
  
  arg1 = (Smart3dMap::triangle *)jarg1; 
  result = (int) ((arg1)->b);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_triangle_c_set(void * jarg1, int jarg2) {
  Smart3dMap::triangle *arg1 = (Smart3dMap::triangle *) 0 ;
  int arg2 ;
  
  arg1 = (Smart3dMap::triangle *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->c = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_triangle_c_get(void * jarg1) {
  int jresult ;
  Smart3dMap::triangle *arg1 = (Smart3dMap::triangle *) 0 ;
  int result;
  
  arg1 = (Smart3dMap::triangle *)jarg1; 
  result = (int) ((arg1)->c);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_triangle() {
  void * jresult ;
  Smart3dMap::triangle *result = 0 ;
  
  result = (Smart3dMap::triangle *)new Smart3dMap::triangle();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_triangle(void * jarg1) {
  Smart3dMap::triangle *arg1 = (Smart3dMap::triangle *) 0 ;
  
  arg1 = (Smart3dMap::triangle *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_Clear(void * jarg1) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_Add(void * jarg1, void * jarg2) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  Smart3dMap::point3d *arg2 = 0 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (Smart3dMap::point3d *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Smart3dMap::point3d const & type is null", 0);
    return ;
  } 
  (arg1)->push_back((Smart3dMap::point3d const &)*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_vec3ds_size(void * jarg1) {
  unsigned long jresult ;
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  vector< Smart3dMap::point3d >::size_type result;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  result = ((vector< Smart3dMap::point3d > const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_vec3ds_capacity(void * jarg1) {
  unsigned long jresult ;
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  vector< Smart3dMap::point3d >::size_type result;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  result = ((vector< Smart3dMap::point3d > const *)arg1)->capacity();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_reserve(void * jarg1, unsigned long jarg2) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  vector< Smart3dMap::point3d >::size_type arg2 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (vector< Smart3dMap::point3d >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_vec3ds__SWIG_0() {
  void * jresult ;
  vector< Smart3dMap::point3d > *result = 0 ;
  
  result = (vector< Smart3dMap::point3d > *)new vector< Smart3dMap::point3d >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_vec3ds__SWIG_1(void * jarg1) {
  void * jresult ;
  std::vector< Smart3dMap::point3d > *arg1 = 0 ;
  vector< Smart3dMap::point3d > *result = 0 ;
  
  arg1 = (std::vector< Smart3dMap::point3d > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Smart3dMap::point3d > const & type is null", 0);
    return 0;
  } 
  result = (vector< Smart3dMap::point3d > *)new vector< Smart3dMap::point3d >((std::vector< Smart3dMap::point3d > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_vec3ds__SWIG_2(int jarg1) {
  void * jresult ;
  int arg1 ;
  vector< Smart3dMap::point3d > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (vector< Smart3dMap::point3d > *)new_vector_Sl_Smart3dMap_point3d_Sg___SWIG_2(arg1);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_vec3ds_getitemcopy(void * jarg1, int jarg2) {
  void * jresult ;
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  int arg2 ;
  Smart3dMap::point3d result;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = vector_Sl_Smart3dMap_point3d_Sg__getitemcopy(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = new Smart3dMap::point3d((const Smart3dMap::point3d &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_vec3ds_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  int arg2 ;
  Smart3dMap::point3d *result = 0 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (Smart3dMap::point3d *) &vector_Sl_Smart3dMap_point3d_Sg__getitem(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_setitem(void * jarg1, int jarg2, void * jarg3) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  int arg2 ;
  Smart3dMap::point3d *arg3 = 0 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Smart3dMap::point3d *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Smart3dMap::point3d const & type is null", 0);
    return ;
  } 
  try {
    vector_Sl_Smart3dMap_point3d_Sg__setitem(arg1,arg2,(Smart3dMap::point3d const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_AddRange(void * jarg1, void * jarg2) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  std::vector< Smart3dMap::point3d > *arg2 = 0 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (std::vector< Smart3dMap::point3d > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Smart3dMap::point3d > const & type is null", 0);
    return ;
  } 
  vector_Sl_Smart3dMap_point3d_Sg__AddRange(arg1,(vector< Smart3dMap::point3d > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_vec3ds_GetRange(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< Smart3dMap::point3d > *result = 0 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< Smart3dMap::point3d > *)vector_Sl_Smart3dMap_point3d_Sg__GetRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_Insert(void * jarg1, int jarg2, void * jarg3) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  int arg2 ;
  Smart3dMap::point3d *arg3 = 0 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Smart3dMap::point3d *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Smart3dMap::point3d const & type is null", 0);
    return ;
  } 
  try {
    vector_Sl_Smart3dMap_point3d_Sg__Insert(arg1,arg2,(Smart3dMap::point3d const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_InsertRange(void * jarg1, int jarg2, void * jarg3) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  int arg2 ;
  std::vector< Smart3dMap::point3d > *arg3 = 0 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Smart3dMap::point3d > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Smart3dMap::point3d > const & type is null", 0);
    return ;
  } 
  try {
    vector_Sl_Smart3dMap_point3d_Sg__InsertRange(arg1,arg2,(vector< Smart3dMap::point3d > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_RemoveAt(void * jarg1, int jarg2) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  int arg2 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    vector_Sl_Smart3dMap_point3d_Sg__RemoveAt(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_RemoveRange(void * jarg1, int jarg2, int jarg3) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    vector_Sl_Smart3dMap_point3d_Sg__RemoveRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void * SWIGSTDCALL CSharp_vec3ds_Repeat(void * jarg1, int jarg2) {
  void * jresult ;
  Smart3dMap::point3d *arg1 = 0 ;
  int arg2 ;
  std::vector< Smart3dMap::point3d > *result = 0 ;
  
  arg1 = (Smart3dMap::point3d *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Smart3dMap::point3d const & type is null", 0);
    return 0;
  } 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Smart3dMap::point3d > *)vector_Sl_Smart3dMap_point3d_Sg__Repeat((Smart3dMap::point3d const &)*arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_Reverse__SWIG_0(void * jarg1) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  vector_Sl_Smart3dMap_point3d_Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_Reverse__SWIG_1(void * jarg1, int jarg2, int jarg3) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    vector_Sl_Smart3dMap_point3d_Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_vec3ds_SetRange(void * jarg1, int jarg2, void * jarg3) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  int arg2 ;
  std::vector< Smart3dMap::point3d > *arg3 = 0 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Smart3dMap::point3d > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Smart3dMap::point3d > const & type is null", 0);
    return ;
  } 
  try {
    vector_Sl_Smart3dMap_point3d_Sg__SetRange(arg1,arg2,(vector< Smart3dMap::point3d > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_vec3ds(void * jarg1) {
  vector< Smart3dMap::point3d > *arg1 = (vector< Smart3dMap::point3d > *) 0 ;
  
  arg1 = (vector< Smart3dMap::point3d > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_Clear(void * jarg1) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  (arg1)->clear();
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_Add(void * jarg1, void * jarg2) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  Smart3dMap::triangle *arg2 = 0 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (Smart3dMap::triangle *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Smart3dMap::triangle const & type is null", 0);
    return ;
  } 
  (arg1)->push_back((Smart3dMap::triangle const &)*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_vecTris_size(void * jarg1) {
  unsigned long jresult ;
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  vector< Smart3dMap::triangle >::size_type result;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  result = ((vector< Smart3dMap::triangle > const *)arg1)->size();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_vecTris_capacity(void * jarg1) {
  unsigned long jresult ;
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  vector< Smart3dMap::triangle >::size_type result;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  result = ((vector< Smart3dMap::triangle > const *)arg1)->capacity();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_reserve(void * jarg1, unsigned long jarg2) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  vector< Smart3dMap::triangle >::size_type arg2 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (vector< Smart3dMap::triangle >::size_type)jarg2; 
  (arg1)->reserve(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_vecTris__SWIG_0() {
  void * jresult ;
  vector< Smart3dMap::triangle > *result = 0 ;
  
  result = (vector< Smart3dMap::triangle > *)new vector< Smart3dMap::triangle >();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_vecTris__SWIG_1(void * jarg1) {
  void * jresult ;
  std::vector< Smart3dMap::triangle > *arg1 = 0 ;
  vector< Smart3dMap::triangle > *result = 0 ;
  
  arg1 = (std::vector< Smart3dMap::triangle > *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Smart3dMap::triangle > const & type is null", 0);
    return 0;
  } 
  result = (vector< Smart3dMap::triangle > *)new vector< Smart3dMap::triangle >((std::vector< Smart3dMap::triangle > const &)*arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_vecTris__SWIG_2(int jarg1) {
  void * jresult ;
  int arg1 ;
  vector< Smart3dMap::triangle > *result = 0 ;
  
  arg1 = (int)jarg1; 
  try {
    result = (vector< Smart3dMap::triangle > *)new_vector_Sl_Smart3dMap_triangle_Sg___SWIG_2(arg1);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_vecTris_getitemcopy(void * jarg1, int jarg2) {
  void * jresult ;
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  int arg2 ;
  Smart3dMap::triangle result;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = vector_Sl_Smart3dMap_triangle_Sg__getitemcopy(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = new Smart3dMap::triangle((const Smart3dMap::triangle &)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_vecTris_getitem(void * jarg1, int jarg2) {
  void * jresult ;
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  int arg2 ;
  Smart3dMap::triangle *result = 0 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    result = (Smart3dMap::triangle *) &vector_Sl_Smart3dMap_triangle_Sg__getitem(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_setitem(void * jarg1, int jarg2, void * jarg3) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  int arg2 ;
  Smart3dMap::triangle *arg3 = 0 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Smart3dMap::triangle *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Smart3dMap::triangle const & type is null", 0);
    return ;
  } 
  try {
    vector_Sl_Smart3dMap_triangle_Sg__setitem(arg1,arg2,(Smart3dMap::triangle const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_AddRange(void * jarg1, void * jarg2) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  std::vector< Smart3dMap::triangle > *arg2 = 0 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (std::vector< Smart3dMap::triangle > *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Smart3dMap::triangle > const & type is null", 0);
    return ;
  } 
  vector_Sl_Smart3dMap_triangle_Sg__AddRange(arg1,(vector< Smart3dMap::triangle > const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_vecTris_GetRange(void * jarg1, int jarg2, int jarg3) {
  void * jresult ;
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  int arg2 ;
  int arg3 ;
  std::vector< Smart3dMap::triangle > *result = 0 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    result = (std::vector< Smart3dMap::triangle > *)vector_Sl_Smart3dMap_triangle_Sg__GetRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_Insert(void * jarg1, int jarg2, void * jarg3) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  int arg2 ;
  Smart3dMap::triangle *arg3 = 0 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (Smart3dMap::triangle *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Smart3dMap::triangle const & type is null", 0);
    return ;
  } 
  try {
    vector_Sl_Smart3dMap_triangle_Sg__Insert(arg1,arg2,(Smart3dMap::triangle const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_InsertRange(void * jarg1, int jarg2, void * jarg3) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  int arg2 ;
  std::vector< Smart3dMap::triangle > *arg3 = 0 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Smart3dMap::triangle > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Smart3dMap::triangle > const & type is null", 0);
    return ;
  } 
  try {
    vector_Sl_Smart3dMap_triangle_Sg__InsertRange(arg1,arg2,(vector< Smart3dMap::triangle > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_RemoveAt(void * jarg1, int jarg2) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  int arg2 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (int)jarg2; 
  try {
    vector_Sl_Smart3dMap_triangle_Sg__RemoveAt(arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_RemoveRange(void * jarg1, int jarg2, int jarg3) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    vector_Sl_Smart3dMap_triangle_Sg__RemoveRange(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void * SWIGSTDCALL CSharp_vecTris_Repeat(void * jarg1, int jarg2) {
  void * jresult ;
  Smart3dMap::triangle *arg1 = 0 ;
  int arg2 ;
  std::vector< Smart3dMap::triangle > *result = 0 ;
  
  arg1 = (Smart3dMap::triangle *)jarg1;
  if (!arg1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Smart3dMap::triangle const & type is null", 0);
    return 0;
  } 
  arg2 = (int)jarg2; 
  try {
    result = (std::vector< Smart3dMap::triangle > *)vector_Sl_Smart3dMap_triangle_Sg__Repeat((Smart3dMap::triangle const &)*arg1,arg2);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return 0;
  }
  
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_Reverse__SWIG_0(void * jarg1) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  vector_Sl_Smart3dMap_triangle_Sg__Reverse__SWIG_0(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_Reverse__SWIG_1(void * jarg1, int jarg2, int jarg3) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  try {
    vector_Sl_Smart3dMap_triangle_Sg__Reverse__SWIG_1(arg1,arg2,arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  catch(std::invalid_argument &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentException, (&_e)->what(), "");
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_vecTris_SetRange(void * jarg1, int jarg2, void * jarg3) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  int arg2 ;
  std::vector< Smart3dMap::triangle > *arg3 = 0 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (std::vector< Smart3dMap::triangle > *)jarg3;
  if (!arg3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::vector< Smart3dMap::triangle > const & type is null", 0);
    return ;
  } 
  try {
    vector_Sl_Smart3dMap_triangle_Sg__SetRange(arg1,arg2,(vector< Smart3dMap::triangle > const &)*arg3);
  }
  catch(std::out_of_range &_e) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, 0, (&_e)->what());
    return ;
  }
  
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_vecTris(void * jarg1) {
  vector< Smart3dMap::triangle > *arg1 = (vector< Smart3dMap::triangle > *) 0 ;
  
  arg1 = (vector< Smart3dMap::triangle > *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_gmeParseObj() {
  void * jresult ;
  Smart3dMap::gmeParseObj *result = 0 ;
  
  result = (Smart3dMap::gmeParseObj *)new Smart3dMap::gmeParseObj();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_gmeParseObj(void * jarg1) {
  Smart3dMap::gmeParseObj *arg1 = (Smart3dMap::gmeParseObj *) 0 ;
  
  arg1 = (Smart3dMap::gmeParseObj *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_gmeParseObj_fillPoints(void * jarg1, void * jarg2) {
  Smart3dMap::gmeParseObj *arg1 = (Smart3dMap::gmeParseObj *) 0 ;
  Smart3dMap::vec3dList arg2 ;
  Smart3dMap::vec3dList *argp2 ;
  
  arg1 = (Smart3dMap::gmeParseObj *)jarg1; 
  argp2 = (Smart3dMap::vec3dList *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Smart3dMap::vec3dList", 0);
    return ;
  }
  arg2 = *argp2; 
  (arg1)->fillPoints(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_gmeParseObj_fillTriangles(void * jarg1, void * jarg2) {
  Smart3dMap::gmeParseObj *arg1 = (Smart3dMap::gmeParseObj *) 0 ;
  Smart3dMap::vecTriList arg2 ;
  Smart3dMap::vecTriList *argp2 ;
  
  arg1 = (Smart3dMap::gmeParseObj *)jarg1; 
  argp2 = (Smart3dMap::vecTriList *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Smart3dMap::vecTriList", 0);
    return ;
  }
  arg2 = *argp2; 
  (arg1)->fillTriangles(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_gmeParseObj_setObjName(void * jarg1, char * jarg2) {
  Smart3dMap::gmeParseObj *arg1 = (Smart3dMap::gmeParseObj *) 0 ;
  std::string arg2 ;
  
  arg1 = (Smart3dMap::gmeParseObj *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  (&arg2)->assign(jarg2); 
  (arg1)->setObjName(arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_gmeParseObj_getPointsNum(void * jarg1) {
  int jresult ;
  Smart3dMap::gmeParseObj *arg1 = (Smart3dMap::gmeParseObj *) 0 ;
  int result;
  
  arg1 = (Smart3dMap::gmeParseObj *)jarg1; 
  result = (int)(arg1)->getPointsNum();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_gmeParseObj_getTrianglesNum(void * jarg1) {
  int jresult ;
  Smart3dMap::gmeParseObj *arg1 = (Smart3dMap::gmeParseObj *) 0 ;
  int result;
  
  arg1 = (Smart3dMap::gmeParseObj *)jarg1; 
  result = (int)(arg1)->getTrianglesNum();
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_gmeParseObj_getName(void * jarg1) {
  char * jresult ;
  Smart3dMap::gmeParseObj *arg1 = (Smart3dMap::gmeParseObj *) 0 ;
  std::string result;
  
  arg1 = (Smart3dMap::gmeParseObj *)jarg1; 
  result = (arg1)->getName();
  jresult = SWIG_csharp_string_callback((&result)->c_str()); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_gmeParseObj_getBatchId(void * jarg1) {
  void * jresult ;
  Smart3dMap::gmeParseObj *arg1 = (Smart3dMap::gmeParseObj *) 0 ;
  std::vector< int > result;
  
  arg1 = (Smart3dMap::gmeParseObj *)jarg1; 
  result = (arg1)->getBatchId();
  jresult = new std::vector< int >((const std::vector< int > &)result); 
  return jresult;
}


#ifdef __cplusplus
}
#endif

