%module(directors = "1") SwigCplusplus
%{
	#include "CPlusPlusClass.h"
%}
%feature("director") SimpleCallback;

%include "std_string.i"
%include "std_vector.i"
using namespace std;
%include "CPlusPlusClass.h"